### ISSUE TITLE
After running test.sh, the replicas setting value is not reached And deleting catset fails

### ISSUE THREAD

**Issue by yangjinheng** [metacontroller/metacontroller#144]
My environment:
    K8S: v1.17.14
    Metacontroller: v1.1.1

**Problem1: catset cannot reach the number of copies**

pod logs of metacontroller-0:

~~~bash
[root@node1 ~]# kubectl get pods
NAME              READY   STATUS    RESTARTS   AGE
nginx-backend-0   1/1     Running   0          11m
[root@node1 ~]# kubectl -n metacontroller logs -f --tail 10 metacontroller-0
      }
    }
  },
  "finalizing": false
}
I1229 08:14:54.972159       1 webhook.go:54] DEBUG: webhook timeout: 10s
I1229 08:14:54.982961       1 webhook.go:66] DEBUG: webhook url: http://catset-controller.metacontroller/sync response body: {"status":{"replicas":1,"readyReplicas":1},"children":[{"metadata":{"labels":{"app":"nginx","component":"backend"},"name":"nginx-backend-1"},"spec":{"containers":[{"image":"nginx:stable-alpine","name":"nginx","ports":[{"containerPort":80,"name":"web"}],"volumeMounts":[{"mountPath":"/usr/share/nginx/html","name":"www"}]}],"terminationGracePeriodSeconds":1,"hostname":"nginx-backend-1","subdomain":"nginx-backend","volumes":[{"name":"www","persistentVolumeClaim":{"claimName":"www-nginx-backend-1"}}]},"apiVersion":"v1","kind":"Pod"},{"metadata":{"labels":{"app":"nginx","component":"backend"},"name":"nginx-backend-0"},"spec":{"containers":[{"image":"nginx:stable-alpine","name":"nginx","ports":[{"containerPort":80,"name":"web"}],"volumeMounts":[{"mountPath":"/usr/share/nginx/html","name":"www"}]}],"terminationGracePeriodSeconds":1,"hostname":"nginx-backend-0","subdomain":"nginx-backend","volumes":[{"name":"www","persistentVolumeClaim":{"claimName":"www-nginx-backend-0"}}]},"apiVersion":"v1","kind":"Pod"},{"metadata":{"labels":{"app":"nginx","component":"backend"},"name":"www-nginx-backend-0"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}},"storageClassName":"standard"},"apiVersion":"v1","kind":"PersistentVolumeClaim"},{"metadata":{"labels":{"app":"nginx","component":"backend"},"name":"www-nginx-backend-1"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}},"storageClassName":"standard"},"apiVersion":"v1","kind":"PersistentVolumeClaim"},{"metadata":{"labels":{"app":"nginx","component":"backend"},"name":"www-nginx-backend-2"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}},"storageClassName":"standard"},"apiVersion":"v1","kind":"PersistentVolumeClaim"}]}
I1229 08:14:54.984309       1 webhook.go:66] DEBUG: webhook url: http://catset-controller.metacontroller/sync response body: {"status":{"replicas":1,"readyReplicas":1},"children":[{"metadata":{"labels":{"app":"nginx","component":"backend"},"name":"nginx-backend-1"},"spec":{"containers":[{"image":"nginx:stable-alpine","name":"nginx","ports":[{"containerPort":80,"name":"web"}],"volumeMounts":[{"mountPath":"/usr/share/nginx/html","name":"www"}]}],"terminationGracePeriodSeconds":1,"hostname":"nginx-backend-1","subdomain":"nginx-backend","volumes":[{"name":"www","persistentVolumeClaim":{"claimName":"www-nginx-backend-1"}}]},"apiVersion":"v1","kind":"Pod"},{"metadata":{"labels":{"app":"nginx","component":"backend"},"name":"nginx-backend-0"},"spec":{"containers":[{"image":"nginx:stable-alpine","name":"nginx","ports":[{"containerPort":80,"name":"web"}],"volumeMounts":[{"mountPath":"/usr/share/nginx/html","name":"www"}]}],"terminationGracePeriodSeconds":1,"hostname":"nginx-backend-0","subdomain":"nginx-backend","volumes":[{"name":"www","persistentVolumeClaim":{"claimName":"www-nginx-backend-0"}}]},"apiVersion":"v1","kind":"Pod"},{"metadata":{"labels":{"app":"nginx","component":"backend"},"name":"www-nginx-backend-0"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}},"storageClassName":"standard"},"apiVersion":"v1","kind":"PersistentVolumeClaim"},{"metadata":{"labels":{"app":"nginx","component":"backend"},"name":"www-nginx-backend-1"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}},"storageClassName":"standard"},"apiVersion":"v1","kind":"PersistentVolumeClaim"},{"metadata":{"labels":{"app":"nginx","component":"backend"},"name":"www-nginx-backend-2"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}},"storageClassName":"standard"},"apiVersion":"v1","kind":"PersistentVolumeClaim"}]}
I1229 08:14:54.985102       1 controller_revision.go:277] CatSet default/nginx-backend: updating ControllerRevision catsets.ctl.enisoc.com-4006d259a964ee57dd922da9a45e2c6ed993b02d
E1229 08:14:54.990604       1 controller.go:223] failed to sync CatSet "default/nginx-backend": CatSet default/nginx-backend: can't reconcile ControllerRevisions: can't update ControllerRevision catsets.ctl.enisoc.com-4006d259a964ee57dd922da9a45e2c6ed993b02d for CatSet default/nginx-backend: controllerrevisions.metacontroller.k8s.io "catsets.ctl.enisoc.com-4006d259a964ee57dd922da9a45e2c6ed993b02d" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
~~~

**Problem2: The finalize hook is blocking and the catset deletion fails**

~~~bash
++ kubectl get catsets nginx-backend -o 'jsonpath={.status.readyReplicas}'
+ [[ 0 -eq 3 ]]
+ sleep 1
^C++ cleanup
++ set +e
++ echo 'Clean up...'
Clean up...
++ kubectl patch catsets nginx-backend --type=merge -p '{"metadata":{"finalizers":[]}}'
catset.ctl.enisoc.com/nginx-backend patched
++ kubectl delete -f my-catset.yaml
service "nginx-backend" deleted
catset.ctl.enisoc.com "nginx-backend" deleted
~~~

After deleting finalize hook, catset is deleted successfully

~~~yaml
hooks:
sync:
    webhook:
    url: http://catset-controller.metacontroller/sync
# finalize:
#   webhook:
#     url: http://catset-controller.metacontroller/sync
~~~

kubectl apply -f catset-controller.yaml

~~~bash

^C++ cleanup
++ set +e
++ echo 'Clean up...'
Clean up...
++ kubectl patch catsets nginx-backend --type=merge -p '{"metadata":{"finalizers":[]}}'
catset.ctl.enisoc.com/nginx-backend patched
++ kubectl delete -f my-catset.yaml
service "nginx-backend" deleted
catset.ctl.enisoc.com "nginx-backend" deleted
++ kubectl delete po,pvc -l app=nginx,component=backend
pod "nginx-backend-0" deleted
persistentvolumeclaim "www-nginx-backend-0" deleted
persistentvolumeclaim "www-nginx-backend-1" deleted
persistentvolumeclaim "www-nginx-backend-2" deleted
++ kubectl delete -f catset-controller.yaml
customresourcedefinition.apiextensions.k8s.io "catsets.ctl.enisoc.com" deleted
compositecontroller.metacontroller.k8s.io "catset-controller" deleted
deployment.apps "catset-controller" deleted
service "catset-controller" deleted
++ kubectl delete configmap catset-controller -n metacontroller
configmap "catset-controller" deleted

~~~

**Comment by grzesuav** [comment]
thanks for reporting, could you add :
1. output of `kubectl describe` and the pod of catset controller
2. how you set up your local k8s cluster ?

**Comment by yangjinheng** [comment]
1. kubectl describe 
~~~bash
[root@node1 ~]# kubectl -n metacontroller describe pods catset-controller-7ff947dbd5-wnv5j
Name:         catset-controller-7ff947dbd5-wnv5j
Namespace:    metacontroller
Priority:     0
Node:         172.16.0.103/172.16.0.103
Start Time:   Tue, 29 Dec 2020 20:58:16 +0800
Labels:       app=catset-controller
              pod-template-hash=7ff947dbd5
Annotations:  cni.projectcalico.org/podIP: 10.42.1.44/32
              cni.projectcalico.org/podIPs: 10.42.1.44/32
Status:       Running
IP:           10.42.1.44
IPs:
  IP:           10.42.1.44
Controlled By:  ReplicaSet/catset-controller-7ff947dbd5
Containers:
  controller:
    Container ID:   docker://6c42185a6fa75cf119ce53904b2f6365f72c45460e2df412c02b80671d9860e3
    Image:          metacontroller/nodejs-server:0.1
    Image ID:       docker-pullable://metacontroller/nodejs-server@sha256:3481a7fba3dd624e4e45a613be9c7a2b41766f9bd3f3b37c0adf280ea95b4cf6
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Tue, 29 Dec 2020 20:58:28 +0800
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /node/hooks from hooks (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lfcqv (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  hooks:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      catset-controller
    Optional:  false
  default-token-lfcqv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-lfcqv
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age    From                   Message
  ----    ------     ----   ----                   -------
  Normal  Scheduled  7m9s   default-scheduler      Successfully assigned metacontroller/catset-controller-7ff947dbd5-wnv5j to 172.16.0.103
  Normal  Pulling    7m7s   kubelet, 172.16.0.103  Pulling image "metacontroller/nodejs-server:0.1"
  Normal  Pulled     6m58s  kubelet, 172.16.0.103  Successfully pulled image "metacontroller/nodejs-server:0.1"
  Normal  Created    6m57s  kubelet, 172.16.0.103  Created container controller
  Normal  Started    6m57s  kubelet, 172.16.0.103  Started container controller

~~~

~~~bash
[root@node1 ~]# kubectl -n metacontroller describe pods metacontroller-0
Name:         metacontroller-0
Namespace:    metacontroller
Priority:     0
Node:         172.16.0.103/172.16.0.103
Start Time:   Fri, 25 Dec 2020 18:35:17 +0800
Labels:       app.kubernetes.io/name=metacontroller
              controller-revision-hash=metacontroller-5c984548cd
              statefulset.kubernetes.io/pod-name=metacontroller-0
Annotations:  cni.projectcalico.org/podIP: 10.42.1.43/32
              cni.projectcalico.org/podIPs: 10.42.1.43/32
Status:       Running
IP:           10.42.1.43
IPs:
  IP:           10.42.1.43
Controlled By:  StatefulSet/metacontroller
Containers:
  metacontroller:
    Container ID:  docker://83d092f9f4507be722cf297b95fc9541e5bfa47b1e9faa16e6ec27698cb1c651
    Image:         metacontrollerio/metacontroller:v1.0.0
    Image ID:      docker-pullable://metacontrollerio/metacontroller@sha256:583ae67a22462e78278cae577b4a1aa17e43ad0b5f800fd664cdab3078cf3515
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/bin/metacontroller
    Args:
      --logtostderr
      -v=6
      --discovery-interval=20s
    State:          Running
      Started:      Tue, 29 Dec 2020 20:54:25 +0800
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 29 Dec 2020 15:26:06 +0800
      Finished:     Tue, 29 Dec 2020 17:06:39 +0800
    Ready:          True
    Restart Count:  5
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from metacontroller-token-r9vc4 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  metacontroller-token-r9vc4:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  metacontroller-token-r9vc4
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason          Age                    From                   Message
  ----    ------          ----                   ----                   -------
  Normal  SandboxChanged  5m57s (x2 over 6m10s)  kubelet, 172.16.0.103  Pod sandbox changed, it will be killed and re-created.
  Normal  Pulled          5m20s                  kubelet, 172.16.0.103  Container image "metacontrollerio/metacontroller:v1.0.0" already present on machine
  Normal  Created         5m20s                  kubelet, 172.16.0.103  Created container metacontroller
  Normal  Started         5m17s                  kubelet, 172.16.0.103  Started container metacontroller

~~~

2.  Cluster information

+ A three-node cluster deployed using [rke](https://github.com/rancher/rke)
+ Use the default method to deploy metacontroller, I noticed that metacontroller controls the cluster by reading serviceAccountName

~~~bash
[root@node1 ~]# kubectl get nodes
NAME           STATUS   ROLES               AGE    VERSION
172.16.0.101   Ready    controlplane,etcd   4d4h   v1.17.14
172.16.0.102   Ready    worker              4d4h   v1.17.14
172.16.0.103   Ready    worker              4d4h   v1.17.14
~~~

~~~bash
[root@node1 ~]# kubectl get clusterinformations default -o yaml
apiVersion: crd.projectcalico.org/v1
kind: ClusterInformation
metadata:
  annotations:
    projectcalico.org/metadata: '{"uid":"b9111d07-0cc6-4abe-9a37-ca72dcafc885","creationTimestamp":"2020-12-25T09:11:27Z"}'
  creationTimestamp: "2020-12-25T09:11:27Z"
  generation: 1
  name: default
  resourceVersion: "640"
  selfLink: /apis/crd.projectcalico.org/v1/clusterinformations/default
  uid: b7fc2047-c51d-4288-a115-908225231426
spec:
  calicoVersion: v3.13.4
  clusterGUID: 47ef04313338403e8fb4691147af9331
  clusterType: k8s,canal,rancher,kdd
  datastoreReady: true
~~~

Please point out if there is anything that is not detailed.

**Comment by grzesuav** [comment]
hi @yangjinheng , I have ran all test suite locally on `kind` with cluster 1.18.2, the only problem I noticed was different representation of string in `test.sh`, fixed in https://github.com/metacontroller/metacontroller/pull/148


Can you check if it helps ? 


Also, can you run this example on kind cluster with kubernetes version you were using ?

**Comment by yangjinheng** [comment]
# Thank you very much for your answer

## i tested it in two deployment modes: RKE and minicube，The problem remains

i may have given you the wrong direction from the beginning, but I think the following log is probably the right one
~~~bash
E0113 03:55:35.407841 1 controller.go:225] Fails to sync CatSet "default/nginx-backend": CatSet default/nginx-backend: can't reconcile ControllerRevisions: can't update ControllerRevision catsets.ctl.enisoc.com-0acc70ed3c73f6f4f6db95fc919a8e5c48d7801f for CatSet default/nginx-backend: controllerrevisions.metacontroller.k8s.io "catsets.ctl.enisoc.com-0acc70ed3c73f6f4f6db95fc919a8e5c48d7801f" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
~~~

# Here's how I tested it

# env
* RKE deploys the K8S
~~~bash
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.14", GitCommit:"f238f5142728be4033c37aa0ad69bf806090beae", GitTreeState:"clean", BuildDate:"2020-11-11T13:11:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.14", GitCommit:"f238f5142728be4033c37aa0ad69bf806090beae", GitTreeState:"clean", BuildDate:"2020-11-11T13:03:54Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
~~~

* minikube deploys the K8S
~~~bash
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
~~~

# pull new version
~~~bash
git clone https://github.com/grzesuav/metacontroller.git
cd metacontroller
git checkout 2381dbd
~~~

# upgrade
~~~bash
kubectl kustomize manifests/production/ | kubectl apply -f -
~~~

# localization required modifications
~~~bash
cd examples/catset
## edit my-catset.yaml and add storageClassName: Standard
## Edit my-catset.yaml to change image to nginx:stable-alpine
~~~

# run test.sh
~~~bash
bash test.sh
~~~

## enter the condition loop, and output
++ kubectl get catsets nginx-backend -o 'jsonpath={.status.readyReplicas}'
+ [[ 0 -eq 3 ]]
+ sleep 1
++ kubectl get catsets nginx-backend -o 'jsonpath={.status.readyReplicas}'
+ [[ 0 -eq 3 ]]
+ sleep 1
++ kubectl get catsets nginx-backend -o 'jsonpath={.status.readyReplicas}'
+ [[ 0 -eq 3 ]]
+ sleep 1
++ kubectl get catsets nginx-backend -o 'jsonpath={.status.readyReplicas}'
+ [[ 0 -eq 3 ]]
+ sleep 1
++ kubectl get catsets nginx-backend -o 'jsonpath={.status.readyReplicas}'
+ [[ 0 -eq 3 ]]
+ sleep 1

### kubectl get pods // The number of copies is not reached
~~~bash
NAME              READY   STATUS    RESTARTS   AGE
nginx-backend-0   1/1     Running   0          8m31s
~~~

### kubectl -n metacontroller logs -f metacontroller-0
~~~bash
I0113 03:52:29.093508       1 controller.go:309] CatSet default/nginx-backend: child Pod nginx-backend-0 created or updated
I0113 03:52:29.093565       1 controller.go:408] sync CatSet default/nginx-backend
I0113 03:52:29.097917       1 controller_revision.go:277] CatSet default/nginx-backend: updating ControllerRevision catsets.ctl.enisoc.com-0acc70ed3c73f6f4f6db95fc919a8e5c48d7801f
E0113 03:52:29.127775       1 controller.go:225] failed to sync CatSet "default/nginx-backend": CatSet default/nginx-backend: can't reconcile ControllerRevisions: can't update ControllerRevision catsets.ctl.enisoc.com-0acc70ed3c73f6f4f6db95fc919a8e5c48d7801f for CatSet default/nginx-backend: controllerrevisions.metacontroller.k8s.io "catsets.ctl.enisoc.com-0acc70ed3c73f6f4f6db95fc919a8e5c48d7801f" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0113 03:52:29.139628       1 controller.go:309] CatSet default/nginx-backend: child Pod nginx-backend-0 created or updated
I0113 03:52:29.139664       1 controller.go:408] sync CatSet default/nginx-backend
I0113 03:52:29.143919       1 controller_revision.go:277] CatSet default/nginx-backend: updating ControllerRevision catsets.ctl.enisoc.com-0acc70ed3c73f6f4f6db95fc919a8e5c48d7801f
E0113 03:52:29.167011       1 controller.go:225] failed to sync CatSet "default/nginx-backend": CatSet default/nginx-backend: can't reconcile ControllerRevisions: can't update ControllerRevision catsets.ctl.enisoc.com-0acc70ed3c73f6f4f6db95fc919a8e5c48d7801f for CatSet default/nginx-backend: controllerrevisions.metacontroller.k8s.io "catsets.ctl.enisoc.com-0acc70ed3c73f6f4f6db95fc919a8e5c48d7801f" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0113 03:52:31.029950       1 controller.go:408] sync CatSet default/nginx-backend
I0113 03:52:31.040910       1 controller_revision.go:277] CatSet default/nginx-backend: updating ControllerRevision catsets.ctl.enisoc.com-0acc70ed3c73f6f4f6db95fc919a8e5c48d7801f
E0113 03:52:31.048194       1 controller.go:225] failed to sync CatSet "default/nginx-backend": CatSet default/nginx-backend: can't reconcile ControllerRevisions: can't update ControllerRevision catsets.ctl.enisoc.com-0acc70ed3c73f6f4f6db95fc919a8e5c48d7801f for CatSet default/nginx-backend: controllerrevisions.metacontroller.k8s.io "catsets.ctl.enisoc.com-0acc70ed3c73f6f4f6db95fc919a8e5c48d7801f" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0113 03:52:31.563311       1 controller.go:309] CatSet default/nginx-backend: child Pod nginx-backend-0 created or updated
I0113 03:52:31.563334       1 controller.go:408] sync CatSet default/nginx-backend
I0113 03:52:31.589266       1 controller_revision.go:277] CatSet default/nginx-backend: updating ControllerRevision catsets.ctl.enisoc.com-0acc70ed3c73f6f4f6db95fc919a8e5c48d7801f
E0113 03:52:31.596975       1 controller.go:225] failed to sync CatSet "default/nginx-backend": CatSet default/nginx-backend: can't reconcile ControllerRevisions: can't update ControllerRevision catsets.ctl.enisoc.com-0acc70ed3c73f6f4f6db95fc919a8e5c48d7801f for CatSet default/nginx-backend: controllerrevisions.metacontroller.k8s.io "catsets.ctl.enisoc.com-0acc70ed3c73f6f4f6db95fc919a8e5c48d7801f" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0113 03:52:32.307978       1 controller.go:309] CatSet default/nginx-backend: child Pod nginx-backend-0 created or updated
I0113 03:52:32.308004       1 controller.go:408] sync CatSet default/nginx-backend
I0113 03:52:32.332972       1 controller_revision.go:277] CatSet default/nginx-backend: updating ControllerRevision catsets.ctl.enisoc.com-0acc70ed3c73f6f4f6db95fc919a8e5c48d7801f
E0113 03:52:32.339418       1 controller.go:225] failed to sync CatSet "default/nginx-backend": CatSet default/nginx-backend: can't reconcile ControllerRevisions: can't update ControllerRevision catsets.ctl.enisoc.com-0acc70ed3c73f6f4f6db95fc919a8e5c48d7801f for CatSet default/nginx-backend: controllerrevisions.metacontroller.k8s.io "catsets.ctl.enisoc.com-0acc70ed3c73f6f4f6db95fc919a8e5c48d7801f" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0113 03:52:51.529165       1 controller.go:408] sync CatSet default/nginx-backend
I0113 03:52:51.544385       1 controller_revision.go:277] CatSet default/nginx-backend: updating ControllerRevision catsets.ctl.enisoc.com-0acc70ed3c73f6f4f6db95fc919a8e5c48d7801f
E0113 03:52:51.550845       1 controller.go:225] failed to sync CatSet "default/nginx-backend": CatSet default/nginx-backend: can't reconcile ControllerRevisions: can't update ControllerRevision catsets.ctl.enisoc.com-0acc70ed3c73f6f4f6db95fc919a8e5c48d7801f for CatSet default/nginx-backend: controllerrevisions.metacontroller.k8s.io "catsets.ctl.enisoc.com-0acc70ed3c73f6f4f6db95fc919a8e5c48d7801f" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0113 03:55:35.391610       1 controller.go:408] sync CatSet default/nginx-backend
I0113 03:55:35.401753       1 controller_revision.go:277] CatSet default/nginx-backend: updating ControllerRevision catsets.ctl.enisoc.com-0acc70ed3c73f6f4f6db95fc919a8e5c48d7801f
E0113 03:55:35.407841       1 controller.go:225] failed to sync CatSet "default/nginx-backend": CatSet default/nginx-backend: can't reconcile ControllerRevisions: can't update ControllerRevision catsets.ctl.enisoc.com-0acc70ed3c73f6f4f6db95fc919a8e5c48d7801f for CatSet default/nginx-backend: controllerrevisions.metacontroller.k8s.io "catsets.ctl.enisoc.com-0acc70ed3c73f6f4f6db95fc919a8e5c48d7801f" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
~~~

## i can only CRTL + C, but block multiple times

~~~bash
++ kubectl get catsets nginx-backend -o 'jsonpath={.status.readyReplicas}'
+ [[ 0 -eq 3 ]]
+ sleep 1
++ kubectl get catsets nginx-backend -o 'jsonpath={.status.readyReplicas}'
+ [[ 0 -eq 3 ]]
+ sleep 1
^C++ cleanup
++ set +e
++ echo 'Clean up...'
Clean up...
++ kubectl patch catsets nginx-backend --type=merge -p '{"metadata":{"finalizers":[]}}'
catset.ctl.enisoc.com/nginx-backend patched
++ kubectl delete -f my-catset.yaml
service "nginx-backend" deleted
catset.ctl.enisoc.com "nginx-backend" deleted
/* blocking */

^C++ kubectl delete po,pvc -l app=nginx,component=backend
pod "nginx-backend-0" deleted
persistentvolumeclaim "www-nginx-backend-0" deleted
persistentvolumeclaim "www-nginx-backend-1" deleted
persistentvolumeclaim "www-nginx-backend-2" deleted
++ kubectl delete -f catset-controller.yaml
customresourcedefinition.apiextensions.k8s.io "catsets.ctl.enisoc.com" deleted
compositecontroller.metacontroller.k8s.io "catset-controller" deleted
deployment.apps "catset-controller" deleted
service "catset-controller" deleted
/* blocking */

^C++ kubectl delete configmap catset-controller -n metacontroller
configmap "catset-controller" deleted
~~~

### kubectl -n metacontroller logs -f metacontroller-0
~~~bash
I0113 06:23:27.108473       1 controller.go:309] CatSet default/nginx-backend: child Pod nginx-backend-0 created or updated
I0113 06:23:27.108498       1 controller.go:408] sync CatSet default/nginx-backend
I0113 06:23:27.206022       1 controller_revision.go:277] CatSet default/nginx-backend: updating ControllerRevision catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341
E0113 06:23:27.211329       1 controller.go:225] failed to sync CatSet "default/nginx-backend": CatSet default/nginx-backend: can't reconcile ControllerRevisions: can't update ControllerRevision catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341 for CatSet default/nginx-backend: controllerrevisions.metacontroller.k8s.io "catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0113 06:23:28.084672       1 controller.go:309] CatSet default/nginx-backend: child Pod nginx-backend-0 created or updated
I0113 06:23:28.084697       1 controller.go:408] sync CatSet default/nginx-backend
I0113 06:23:28.092662       1 controller_revision.go:277] CatSet default/nginx-backend: updating ControllerRevision catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341
E0113 06:23:28.101499       1 controller.go:225] failed to sync CatSet "default/nginx-backend": CatSet default/nginx-backend: can't reconcile ControllerRevisions: can't update ControllerRevision catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341 for CatSet default/nginx-backend: controllerrevisions.metacontroller.k8s.io "catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0113 06:23:36.227673       1 controller.go:408] sync CatSet default/nginx-backend
I0113 06:23:36.257955       1 controller_revision.go:277] CatSet default/nginx-backend: updating ControllerRevision catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341
E0113 06:23:36.265460       1 controller.go:225] failed to sync CatSet "default/nginx-backend": CatSet default/nginx-backend: can't reconcile ControllerRevisions: can't update ControllerRevision catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341 for CatSet default/nginx-backend: controllerrevisions.metacontroller.k8s.io "catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update

/* 1. Ctrl + C */
I0113 06:24:07.048413       1 controller.go:408] sync CatSet default/nginx-backend
I0113 06:24:07.086627       1 controller_revision.go:277] CatSet default/nginx-backend: updating ControllerRevision catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341
E0113 06:24:07.099306       1 controller.go:225] failed to sync CatSet "default/nginx-backend": CatSet default/nginx-backend: can't reconcile ControllerRevisions: can't update ControllerRevision catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341 for CatSet default/nginx-backend: controllerrevisions.metacontroller.k8s.io "catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0113 06:24:07.099356       1 controller.go:408] sync CatSet default/nginx-backend
I0113 06:24:07.157731       1 controller_revision.go:277] CatSet default/nginx-backend: updating ControllerRevision catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341
E0113 06:24:07.165232       1 controller.go:225] failed to sync CatSet "default/nginx-backend": CatSet default/nginx-backend: can't reconcile ControllerRevisions: can't update ControllerRevision catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341 for CatSet default/nginx-backend: controllerrevisions.metacontroller.k8s.io "catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0113 06:24:07.331209       1 controller.go:408] sync CatSet default/nginx-backend
I0113 06:24:07.341562       1 controller_revision.go:277] CatSet default/nginx-backend: updating ControllerRevision catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341
E0113 06:24:07.382633       1 controller.go:225] failed to sync CatSet "default/nginx-backend": CatSet default/nginx-backend: can't reconcile ControllerRevisions: can't update ControllerRevision catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341 for CatSet default/nginx-backend: controllerrevisions.metacontroller.k8s.io "catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update

/* 2. Ctrl + C */
I0113 06:26:54.989742       1 controller.go:370] CatSet default/nginx-backend: child Pod nginx-backend-0 deleted
I0113 06:26:54.989762       1 controller.go:408] sync CatSet default/nginx-backend
I0113 06:26:55.059180       1 controller.go:370] CatSet default/nginx-backend: child PersistentVolumeClaim www-nginx-backend-0 deleted
I0113 06:26:55.069374       1 controller_revision.go:277] CatSet default/nginx-backend: updating ControllerRevision catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341
I0113 06:26:55.070110       1 controller.go:370] CatSet default/nginx-backend: child PersistentVolumeClaim www-nginx-backend-1 deleted
I0113 06:26:55.135285       1 controller.go:370] CatSet default/nginx-backend: child PersistentVolumeClaim www-nginx-backend-2 deleted
E0113 06:26:55.135456       1 controller.go:225] failed to sync CatSet "default/nginx-backend": CatSet default/nginx-backend: can't reconcile ControllerRevisions: can't update ControllerRevision catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341 for CatSet default/nginx-backend: controllerrevisions.metacontroller.k8s.io "catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0113 06:26:55.135517       1 controller.go:408] sync CatSet default/nginx-backend
I0113 06:26:55.145112       1 controller_revision.go:277] CatSet default/nginx-backend: updating ControllerRevision catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341
E0113 06:26:55.165367       1 controller.go:225] failed to sync CatSet "default/nginx-backend": CatSet default/nginx-backend: can't reconcile ControllerRevisions: can't update ControllerRevision catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341 for CatSet default/nginx-backend: controllerrevisions.metacontroller.k8s.io "catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0113 06:26:55.177401       1 controller.go:370] CatSet default/nginx-backend: child PersistentVolumeClaim www-nginx-backend-1 deleted
I0113 06:26:55.177431       1 controller.go:408] sync CatSet default/nginx-backend
I0113 06:26:55.182920       1 controller_revision.go:277] CatSet default/nginx-backend: updating ControllerRevision catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341
E0113 06:26:55.227560       1 controller.go:225] failed to sync CatSet "default/nginx-backend": CatSet default/nginx-backend: can't reconcile ControllerRevisions: can't update ControllerRevision catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341 for CatSet default/nginx-backend: controllerrevisions.metacontroller.k8s.io "catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0113 06:26:55.244673       1 controller.go:370] CatSet default/nginx-backend: child PersistentVolumeClaim www-nginx-backend-2 deleted
I0113 06:26:55.244703       1 controller.go:408] sync CatSet default/nginx-backend
I0113 06:26:55.247448       1 controller_revision.go:277] CatSet default/nginx-backend: updating ControllerRevision catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341
E0113 06:26:55.270379       1 controller.go:225] failed to sync CatSet "default/nginx-backend": CatSet default/nginx-backend: can't reconcile ControllerRevisions: can't update ControllerRevision catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341 for CatSet default/nginx-backend: controllerrevisions.metacontroller.k8s.io "catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0113 06:26:56.507918       1 controller.go:370] CatSet default/nginx-backend: child Pod nginx-backend-0 deleted
I0113 06:26:56.507950       1 controller.go:408] sync CatSet default/nginx-backend
I0113 06:26:56.525370       1 controller_revision.go:277] CatSet default/nginx-backend: updating ControllerRevision catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341
E0113 06:26:56.530188       1 controller.go:225] failed to sync CatSet "default/nginx-backend": CatSet default/nginx-backend: can't reconcile ControllerRevisions: can't update ControllerRevision catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341 for CatSet default/nginx-backend: controllerrevisions.metacontroller.k8s.io "catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0113 06:26:57.516789       1 controller.go:370] CatSet default/nginx-backend: child Pod nginx-backend-0 deleted
I0113 06:26:57.516822       1 controller.go:408] sync CatSet default/nginx-backend
I0113 06:26:57.576842       1 controller.go:370] CatSet default/nginx-backend: child PersistentVolumeClaim www-nginx-backend-0 deleted
I0113 06:26:57.596089       1 controller.go:370] CatSet default/nginx-backend: child Pod nginx-backend-0 deleted
I0113 06:26:57.600153       1 controller_revision.go:277] CatSet default/nginx-backend: updating ControllerRevision catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341
E0113 06:26:57.649729       1 controller.go:225] failed to sync CatSet "default/nginx-backend": CatSet default/nginx-backend: can't reconcile ControllerRevisions: can't update ControllerRevision catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341 for CatSet default/nginx-backend: controllerrevisions.metacontroller.k8s.io "catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0113 06:26:57.649833       1 controller.go:408] sync CatSet default/nginx-backend
I0113 06:26:57.657183       1 controller_revision.go:277] CatSet default/nginx-backend: updating ControllerRevision catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341
E0113 06:26:57.700263       1 controller.go:225] failed to sync CatSet "default/nginx-backend": CatSet default/nginx-backend: can't reconcile ControllerRevisions: can't update ControllerRevision catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341 for CatSet default/nginx-backend: controllerrevisions.metacontroller.k8s.io "catsets.ctl.enisoc.com-cc0cf9d102af8704539bce3cf948a4db0eff0341" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0113 06:26:57.804271       1 metacontroller.go:152] sync CompositeController catset-controller
I0113 06:26:57.804293       1 metacontroller.go:156] CompositeController catset-controller has been deleted
I0113 06:26:57.804316       1 controller.go:193] Shutting down CatSet CompositeController
I0113 06:26:57.804323       1 factory.go:89] Unsubscribed from shared informer for pods in v1 (total subscribers now 0)
I0113 06:26:57.804326       1 factory.go:98] Stopping shared informer for pods in v1 (no more subscribers)
I0113 06:26:57.804330       1 factory.go:89] Unsubscribed from shared informer for persistentvolumeclaims in v1 (total subscribers now 0)
I0113 06:26:57.804333       1 factory.go:98] Stopping shared informer for persistentvolumeclaims in v1 (no more subscribers)
I0113 06:26:57.804336       1 factory.go:89] Unsubscribed from shared informer for catsets in ctl.enisoc.com/v1 (total subscribers now 0)
I0113 06:26:57.804338       1 factory.go:98] Stopping shared informer for catsets in ctl.enisoc.com/v1 (no more subscribers)

/* 3. Ctrl + C */
null
~~~

**Comment by grzesuav** [comment]
Thanks for detailed log :)

Will try to recreate on `1.17.14`

**Comment by grzesuav** [comment]
Was able to reproduce it :
```
I0115 20:03:31.242207       1 controller.go:408] sync CatSet metacontroller/nginx-backend
I0115 20:03:31.245659       1 controller_revision.go:277] CatSet metacontroller/nginx-backend: updating ControllerRevision catsets.ctl.enisoc.com-dea0e913d79aa7a8a19871c3130edf76d4c10637
E0115 20:03:31.248436       1 controller.go:225] failed to sync CatSet "metacontroller/nginx-backend": CatSet metacontroller/nginx-backend: can't reconcile ControllerRevisions: can't update ControllerRevision catsets.ctl.enisoc.com-dea0e913d79aa7a8a19871c3130edf76d4c10637 for CatSet metacontroller/nginx-backend: controllerrevisions.metacontroller.k8s.io "catsets.ctl.enisoc.com-dea0e913d79aa7a8a19871c3130edf76d4c10637" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update

```


after I finish current in-progress MR's I will try to debug it

**Comment by grzesuav** [comment]
some reading - https://github.com/kubernetes/kubernetes/issues/70674

**Comment by grzesuav** [comment]
need to confirm actual cause, it might be because test itself is doing a `patch` operation, and as`metacontroller` sees older version of resource it gets the error as described (i.e. https://feichashao.com/kubectl-apply-fail/), need to do some more digging

**Comment by Rekseto** [comment]
This test just confirms the problem. In our cluster K8s version: 1.19.3 problem seems the same. CatSet will create just one Pod and after then iMetacontroller throws the error.

Metacontroller just can not update CRD readyReplicas status.

Any updates on this problem? @grzesuav

**Comment by grzesuav** [comment]
yes, I believe the root cause is as described in https://github.com/metacontroller/metacontroller/issues/144#issuecomment-763057918 , need to target fix for that

**Comment by grzesuav** [comment]
@Rekseto could you attach metacontroller log ? It would be helpful to see it has the same cause

**Comment by grzesuav** [comment]
I need to dig bit the issue, it isn't 100% reproductible, but definitely happens. 

Some remarks :
* problem occurs when, by some reason, object `ControllerRevision` has `metadata.resourceVersion` is set
* when we processing `syncRevisions`, we do deep copy on `ControllerRevisions`, which does not preserve all fields on metadata, so on copy we want to update, `resourceVersion` is not set - what is causing problem with update 

When I added  quickfix, which was adding `metadata.resourceVersion` when it was present on older copy, but missing on new one. is makes tess progress, till the moment it should be deleted. What happens there is :
* parent is deleted
* `syncRevisions` gets hotloop, as it tries to `createRevision`, which actually exists
Need to investigate further.

**Comment by AmitKumarDas** [comment]
How about setting the test finalizer during definition itself. In other words let the test finalizer be set in yaml. Test.sh file can still continue to remove this finalizer at the end.

**Comment by grzesuav** [comment]
> How about setting the test finalizer during definition itself. In other words let the test finalizer be set in yaml. Test.sh file can still continue to remove this finalizer at the end.

the finalizer isn't a problem here - when I applied my patch, whole test is working till :
```
kubectl delete $cs nginx-backend --wait=false
```
(parent resource is being deleted), and later it retries, as it want to create `ControllerRevision` which already exists, but it does not see it.

**Comment by grzesuav** [comment]
The situation during last `sync` is as follows :
* parent `CatSet` has been deleted 
```yaml
kind: CatSet
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"ctl.enisoc.com/v1","kind":"CatSet","metadata":{"annotations":{},"name":"nginx-backend","namespace":"metacontroller"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"nginx"}},"serviceName":"nginx-backend","template":{"metadata":{"labels":{"app":"nginx","component":"backend"}},"spec":{"containers":[{"image":"gcr.io/google_containers/nginx-slim:0.8","name":"nginx","ports":[{"containerPort":80,"name":"web"}],"volumeMounts":[{"mountPath":"/usr/share/nginx/html","name":"www"}]}],"terminationGracePeriodSeconds":1}},"volumeClaimTemplates":[{"metadata":{"labels":{"app":"nginx","component":"backend"},"name":"www"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}}}}]}}
    creationTimestamp: "2021-01-26T17:26:22Z"
    deletionGracePeriodSeconds: 0
    deletionTimestamp: "2021-01-26T17:31:58Z"
    finalizers:
    - metacontroller.io/compositecontroller-catset-controller
    generation: 4
    name: nginx-backend
    namespace: metacontroller
    resourceVersion: "10408"
    selfLink: /apis/ctl.enisoc.com/v1/namespaces/metacontroller/catsets/nginx-backend
    uid: 852d7c2a-f655-4c89-906c-f7c68e6f0a44

```
* there exists one `ControllerRevision` :
```yaml
apiVersion: metacontroller.k8s.io/v1alpha1
  children:
  - apiGroup: ""
    kind: Pod
    names:
    - nginx-backend-1
    - nginx-backend-0
  kind: ControllerRevision
  metadata:
    creationTimestamp: "2021-01-26T17:26:23Z"
    generation: 13
    labels:
      app: nginx
      component: backend
      metacontroller.k8s.io/apiGroup: ctl.enisoc.com
      metacontroller.k8s.io/resource: catsets
    name: catsets.ctl.enisoc.com-4bb58ba5b0680f9f4503ce11acc5f40c05bb07b1
    namespace: metacontroller
    resourceVersion: "10351"
    selfLink: /apis/metacontroller.k8s.io/v1alpha1/namespaces/metacontroller/controllerrevisions/catsets.ctl.enisoc.com-4bb58ba5b0680f9f4503ce11acc5f40c05bb07b1
    uid: 7225e1f5-7f5e-4dfa-a583-247731736fab
  parentPatch: {}
```


The exact issue during `sync` is :
* `observed` controllerrevisions are empty (even though it exists, it isn't "picked" as observed)
* `desired` controllerrevisions contains one element (of name the same as existing one) - so it tries to create it - which fails as object exists

So I guess when it would be present in `observed` list it would just try to update it and hopefully worked. The reason why it fails now it unknown, I unfortunately does not know expected behavior of `ControllerRevision` mechanism. 

Sorry for poking @enisoc , maybe you can put some light on this ?

**Comment by grzesuav** [comment]
I also discovered this problem not 100% reproducible, I created several clusters via kind and minikube and it not always happen, not sure what causes this.

**Comment by Rekseto** [comment]
Logs from metacontroller (It's named ArenaSet cause originally I'm developing our version of something like catset but this logs fails for copy-paste from examples from this repo)

```
I0126 22:59:35.588836       1 manage_children.go:254] ArenaSet core-test/test1: creating Pod test1-0
I0126 22:59:35.629152       1 controller.go:309] ArenaSet core-test/test1: child Pod test1-0 created or updated
I0126 22:59:35.637075       1 controller.go:309] ArenaSet core-test/test1: child Pod test1-0 created or updated
I0126 22:59:35.689492       1 controller.go:408] sync ArenaSet core-test/test1
I0126 22:59:35.696772       1 controller_revision.go:277] ArenaSet core-test/test1: updating ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572
I0126 22:59:35.715399       1 controller.go:309] ArenaSet core-test/test1: child Pod test1-0 created or updated
E0126 22:59:35.732065       1 controller.go:225] failed to sync ArenaSet "core-test/test1": ArenaSet core-test/test1: can't reconcile ControllerRevisions: can't update ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572 for ArenaSet core-test/test1: controllerrevisions.metacontroller.k8s.io "arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0126 22:59:35.732191       1 controller.go:408] sync ArenaSet core-test/test1
I0126 22:59:35.736398       1 controller_revision.go:277] ArenaSet core-test/test1: updating ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572
E0126 22:59:35.751163       1 controller.go:225] failed to sync ArenaSet "core-test/test1": ArenaSet core-test/test1: can't reconcile ControllerRevisions: can't update ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572 for ArenaSet core-test/test1: controllerrevisions.metacontroller.k8s.io "arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0126 22:59:35.751210       1 controller.go:408] sync ArenaSet core-test/test1
I0126 22:59:35.756173       1 controller_revision.go:277] ArenaSet core-test/test1: updating ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572
E0126 22:59:35.769004       1 controller.go:225] failed to sync ArenaSet "core-test/test1": ArenaSet core-test/test1: can't reconcile ControllerRevisions: can't update ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572 for ArenaSet core-test/test1: controllerrevisions.metacontroller.k8s.io "arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0126 22:59:35.769076       1 controller.go:408] sync ArenaSet core-test/test1
I0126 22:59:35.775359       1 controller_revision.go:277] ArenaSet core-test/test1: updating ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572
E0126 22:59:35.797987       1 controller.go:225] failed to sync ArenaSet "core-test/test1": ArenaSet core-test/test1: can't reconcile ControllerRevisions: can't update ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572 for ArenaSet core-test/test1: controllerrevisions.metacontroller.k8s.io "arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0126 22:59:35.798060       1 controller.go:408] sync ArenaSet core-test/test1
I0126 22:59:35.803563       1 controller_revision.go:277] ArenaSet core-test/test1: updating ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572
E0126 22:59:35.834702       1 controller.go:225] failed to sync ArenaSet "core-test/test1": ArenaSet core-test/test1: can't reconcile ControllerRevisions: can't update ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572 for ArenaSet core-test/test1: controllerrevisions.metacontroller.k8s.io "arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0126 22:59:35.838221       1 controller.go:408] sync ArenaSet core-test/test1
I0126 22:59:35.844446       1 controller_revision.go:277] ArenaSet core-test/test1: updating ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572
E0126 22:59:35.862532       1 controller.go:225] failed to sync ArenaSet "core-test/test1": ArenaSet core-test/test1: can't reconcile ControllerRevisions: can't update ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572 for ArenaSet core-test/test1: controllerrevisions.metacontroller.k8s.io "arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0126 22:59:36.022743       1 controller.go:408] sync ArenaSet core-test/test1
I0126 22:59:36.030957       1 controller_revision.go:277] ArenaSet core-test/test1: updating ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572
E0126 22:59:36.053986       1 controller.go:225] failed to sync ArenaSet "core-test/test1": ArenaSet core-test/test1: can't reconcile ControllerRevisions: can't update ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572 for ArenaSet core-test/test1: controllerrevisions.metacontroller.k8s.io "arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0126 22:59:36.374204       1 controller.go:408] sync ArenaSet core-test/test1
I0126 22:59:36.380095       1 controller_revision.go:277] ArenaSet core-test/test1: updating ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572
E0126 22:59:36.416078       1 controller.go:225] failed to sync ArenaSet "core-test/test1": ArenaSet core-test/test1: can't reconcile ControllerRevisions: can't update ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572 for ArenaSet core-test/test1: controllerrevisions.metacontroller.k8s.io "arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0126 22:59:36.978466       1 controller.go:309] ArenaSet core-test/test1: child Pod test1-0 created or updated
I0126 22:59:36.978537       1 controller.go:408] sync ArenaSet core-test/test1
I0126 22:59:36.984859       1 controller_revision.go:277] ArenaSet core-test/test1: updating ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572
E0126 22:59:37.010094       1 controller.go:225] failed to sync ArenaSet "core-test/test1": ArenaSet core-test/test1: can't reconcile ControllerRevisions: can't update ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572 for ArenaSet core-test/test1: controllerrevisions.metacontroller.k8s.io "arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0126 22:59:37.056361       1 controller.go:408] sync ArenaSet core-test/test1
I0126 22:59:37.060904       1 controller_revision.go:277] ArenaSet core-test/test1: updating ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572
E0126 22:59:37.077974       1 controller.go:225] failed to sync ArenaSet "core-test/test1": ArenaSet core-test/test1: can't reconcile ControllerRevisions: can't update ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572 for ArenaSet core-test/test1: controllerrevisions.metacontroller.k8s.io "arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0126 22:59:39.436057       1 controller.go:309] ArenaSet core-test/test1: child Pod test1-0 created or updated
I0126 22:59:39.436170       1 controller.go:408] sync ArenaSet core-test/test1
I0126 22:59:39.442482       1 controller_revision.go:277] ArenaSet core-test/test1: updating ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572
E0126 22:59:39.463704       1 controller.go:225] failed to sync ArenaSet "core-test/test1": ArenaSet core-test/test1: can't reconcile ControllerRevisions: can't update ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572 for ArenaSet core-test/test1: controllerrevisions.metacontroller.k8s.io "arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0126 22:59:39.638256       1 controller.go:408] sync ArenaSet core-test/test1
I0126 22:59:39.644795       1 controller_revision.go:277] ArenaSet core-test/test1: updating ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572
E0126 22:59:39.668566       1 controller.go:225] failed to sync ArenaSet "core-test/test1": ArenaSet core-test/test1: can't reconcile ControllerRevisions: can't update ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572 for ArenaSet core-test/test1: controllerrevisions.metacontroller.k8s.io "arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0126 22:59:49.908804       1 controller.go:408] sync ArenaSet core-test/test1
I0126 22:59:49.915865       1 controller_revision.go:277] ArenaSet core-test/test1: updating ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572
E0126 22:59:49.943152       1 controller.go:225] failed to sync ArenaSet "core-test/test1": ArenaSet core-test/test1: can't reconcile ControllerRevisions: can't update ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572 for ArenaSet core-test/test1: controllerrevisions.metacontroller.k8s.io "arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0126 23:00:10.423406       1 controller.go:408] sync ArenaSet core-test/test1
I0126 23:00:10.432206       1 controller_revision.go:277] ArenaSet core-test/test1: updating ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572
E0126 23:00:10.467581       1 controller.go:225] failed to sync ArenaSet "core-test/test1": ArenaSet core-test/test1: can't reconcile ControllerRevisions: can't update ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572 for ArenaSet core-test/test1: controllerrevisions.metacontroller.k8s.io "arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0126 23:00:51.427870       1 controller.go:408] sync ArenaSet core-test/test1
I0126 23:00:51.436021       1 controller_revision.go:277] ArenaSet core-test/test1: updating ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572
E0126 23:00:51.466486       1 controller.go:225] failed to sync ArenaSet "core-test/test1": ArenaSet core-test/test1: can't reconcile ControllerRevisions: can't update ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572 for ArenaSet core-test/test1: controllerrevisions.metacontroller.k8s.io "arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0126 23:01:49.932826       1 controller.go:408] sync ArenaSet metacontroller/test1
I0126 23:01:49.938953       1 controller_revision.go:277] ArenaSet metacontroller/test1: updating ControllerRevision arenasets.craftserve.com-c0758387917618a13bf8434021d5e1b8e5b6f4bd
E0126 23:01:49.958199       1 controller.go:225] failed to sync ArenaSet "metacontroller/test1": ArenaSet metacontroller/test1: can't reconcile ControllerRevisions: can't update ControllerRevision arenasets.craftserve.com-c0758387917618a13bf8434021d5e1b8e5b6f4bd for ArenaSet metacontroller/test1: controllerrevisions.metacontroller.k8s.io "arenasets.craftserve.com-c0758387917618a13bf8434021d5e1b8e5b6f4bd" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
I0126 23:02:13.386787       1 controller.go:408] sync ArenaSet core-test/test1
I0126 23:02:13.394604       1 controller_revision.go:277] ArenaSet core-test/test1: updating ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572
E0126 23:02:13.421302       1 controller.go:225] failed to sync ArenaSet "core-test/test1": ArenaSet core-test/test1: can't reconcile ControllerRevisions: can't update ControllerRevision arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572 for ArenaSet core-test/test1: controllerrevisions.metacontroller.k8s.io "arenasets.craftserve.com-b39de489fbecd46f483261a648a481ef75cbd572" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
```

I encounter an issue while trying to add more than 1 Pod to set cause metacontroller can't update resource replicasReady status :/

**Comment by grzesuav** [comment]
@Rekseto which metacontroller version you used ?

**Comment by Rekseto** [comment]
> @Rekseto which metacontroller version you used ?

latest from master from like 4 days ago? :P

**Comment by grzesuav** [comment]
I did some experiment, seems k8s 1.16 + are affected - https://github.com/grzesuav/metacontroller/actions/runs/691453594

**Comment by grzesuav** [comment]
And I have impression its linked to https://github.com/metacontroller/metacontroller/issues/194 , will try to verify this

**Comment by grzesuav** [comment]
The above issue is not related to current one. 
The impression I have is :
1. Original issue exists as we used cached version of objects, which are changed  on cluster, therefore `resourceVersion` does not match, but I mitigated it.
2. The latter issue exists, as when parent `catset` is marked as `deleted` (have delete timestamp) metacontroller does not include existing `ControllerRevisions` in `observed`, but want to create them. As  it is not in its list - it tries to create it, which cannot be done as object exists on cluster. I will try to fix it, trying not break any other logic

**Comment by grzesuav** [comment]
Also, it seems during `ControllerRevision` update, `ownerReference` is lost...need also check this

**Comment by grzesuav** [comment]
PR with fix - https://github.com/metacontroller/metacontroller/pull/242

**Comment by grzesuav** [comment]
@yangjinheng @Rekseto fix was released in 1.5.7
